# Phase 3 - Member 4 (Robustness Redesign & Prototype Engineer)

This notebook implements vulnerability-driven defense, prototype fine-tuning, re-attack testing, and final deliverables.

In [1]:
import os
import random
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image, ImageFilter

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision.models as models
import torchvision.transforms as transforms
from tqdm import tqdm

In [2]:
# Paths + config
PROJECT_ROOT = Path.cwd().resolve().parents[0] if Path.cwd().name == 'Phase 3' else Path.cwd().resolve()
PHASE3_DIR = PROJECT_ROOT / 'Phase 3'
OUT_DIR = PHASE3_DIR / 'outputs'
OUT_DIR.mkdir(parents=True, exist_ok=True)

DATASET_ROOT = PROJECT_ROOT / 'dataset'
METADATA_PATH = DATASET_ROOT / 'metadata.csv'
M1_RESULTS_PATH = OUT_DIR / 'strategy_results.csv'
M2_RESULTS_PATH = OUT_DIR / 'min_change_summary.csv'
M3_REPORT_PATH = OUT_DIR / 'blindspot_analysis.md'
M3_CORR_PATH = OUT_DIR / 'm3_attack_correlation.csv'
CHECKPOINT_PATH = PROJECT_ROOT / 'Phase1' / 'cifake_resnet18_final.pt'

ROBUST_MODEL_PATH = OUT_DIR / 'robust_model_prototype.pt'
ROBUSTNESS_CSV_PATH = OUT_DIR / 'robustness_comparison.csv'
FINAL_RECO_PATH = OUT_DIR / 'final_recommendation.md'
AFTER_ATTACK_PATH = OUT_DIR / 'm4_strategy_results_robust.csv'
BEFORE_ATTACK_PATH = OUT_DIR / 'm4_strategy_results_original.csv'

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
SEED = 42
IMG_SIZE = 224
BATCH_SIZE = 32
NUM_WORKERS = 0
EPOCHS = 3
MAX_TRAIN_SAMPLES = 4000
MAX_VAL_SAMPLES = 1000

for p in [METADATA_PATH, M1_RESULTS_PATH, M2_RESULTS_PATH, M3_REPORT_PATH, M3_CORR_PATH, CHECKPOINT_PATH]:
    print(p, 'exists=', p.exists())
print('DEVICE=', DEVICE)

/Users/arulkevin/Desktop/psg_hackathon/Feb-2026-Hackathon/dataset/metadata.csv exists= True
/Users/arulkevin/Desktop/psg_hackathon/Feb-2026-Hackathon/Phase 3/outputs/strategy_results.csv exists= True
/Users/arulkevin/Desktop/psg_hackathon/Feb-2026-Hackathon/Phase 3/outputs/min_change_summary.csv exists= True
/Users/arulkevin/Desktop/psg_hackathon/Feb-2026-Hackathon/Phase 3/outputs/blindspot_analysis.md exists= True
/Users/arulkevin/Desktop/psg_hackathon/Feb-2026-Hackathon/Phase 3/outputs/m3_attack_correlation.csv exists= True
/Users/arulkevin/Desktop/psg_hackathon/Feb-2026-Hackathon/Phase1/cifake_resnet18_final.pt exists= True
DEVICE= cpu

In [3]:
# Reproducibility
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

In [4]:
# Load findings and choose defense strategy
m3_corr = pd.read_csv(M3_CORR_PATH)
m3_report_text = M3_REPORT_PATH.read_text(encoding='utf-8')

if m3_corr.empty:
    primary_attack_family = 'Strategy A (Spatial + Frequency)'
else:
    primary_attack_family = m3_corr.sort_values('n_cases', ascending=False).iloc[0]['attack_family']

if 'Strategy A' in str(primary_attack_family):
    defense_strategy = 'strategy_a_robust_aug'
elif 'Strategy B' in str(primary_attack_family):
    defense_strategy = 'strategy_b_noise_aug'
else:
    text_lower = m3_report_text.lower()
    if 'high-frequency' in text_lower or 'texture' in text_lower:
        defense_strategy = 'strategy_a_robust_aug'
    elif 'noise' in text_lower or 'photometric' in text_lower:
        defense_strategy = 'strategy_b_noise_aug'
    else:
        defense_strategy = 'generic_robust_aug'

print('Primary vulnerability family:', primary_attack_family)
print('Selected defense strategy   :', defense_strategy)

Primary vulnerability family: Strategy A (Spatial + Frequency)
Selected defense strategy   : strategy_a_robust_aug

In [5]:
# Dataset + transforms
CIFAR_MEAN = [0.4914, 0.4822, 0.4465]
CIFAR_STD = [0.2023, 0.1994, 0.2010]

class RobustTransform:
    def __init__(self, strategy: str):
        base = [transforms.Resize((IMG_SIZE, IMG_SIZE))]
        if strategy == 'strategy_a_robust_aug':
            aug = [
                transforms.RandomApply([transforms.GaussianBlur(kernel_size=5, sigma=(0.1, 1.5))], p=0.6),
                transforms.RandomGrayscale(p=0.25),
                transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1, hue=0.02),
            ]
        elif strategy == 'strategy_b_noise_aug':
            aug = [
                transforms.ColorJitter(brightness=0.35, contrast=0.35, saturation=0.15, hue=0.03),
                transforms.RandomApply([transforms.GaussianBlur(kernel_size=3, sigma=(0.1, 0.8))], p=0.3),
            ]
        else:
            aug = [
                transforms.RandomApply([transforms.GaussianBlur(kernel_size=3, sigma=(0.1, 1.0))], p=0.4),
                transforms.RandomGrayscale(p=0.15),
                transforms.ColorJitter(brightness=0.25, contrast=0.25, saturation=0.1, hue=0.02),
            ]
        self.tfm = transforms.Compose(base + aug + [
            transforms.ToTensor(),
            transforms.Normalize(mean=CIFAR_MEAN, std=CIFAR_STD)
        ])
    def __call__(self, img):
        return self.tfm(img)

val_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=CIFAR_MEAN, std=CIFAR_STD)
])

class CIFAKEMetadataDataset(Dataset):
    def __init__(self, metadata_df: pd.DataFrame, root_dir: Path, transform=None):
        self.df = metadata_df.reset_index(drop=True)
        self.root_dir = root_dir
        self.transform = transform
    def __len__(self):
        return len(self.df)
    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img_path = self.root_dir / str(row['filepath'])
        img = Image.open(img_path).convert('RGB')
        y = int(row['label'])
        x = self.transform(img) if self.transform is not None else transforms.ToTensor()(img)
        return x, y

meta = pd.read_csv(METADATA_PATH)
train_df = meta[meta['split'] == 'train'].copy().sample(frac=1.0, random_state=SEED)
val_df = meta[meta['split'] == 'val'].copy().sample(frac=1.0, random_state=SEED)

if MAX_TRAIN_SAMPLES and len(train_df) > MAX_TRAIN_SAMPLES:
    n_each = MAX_TRAIN_SAMPLES // 2
    train_df = pd.concat([
        train_df[train_df['label'] == 0].head(n_each),
        train_df[train_df['label'] == 1].head(n_each)
    ]).sample(frac=1.0, random_state=SEED).reset_index(drop=True)

if MAX_VAL_SAMPLES and len(val_df) > MAX_VAL_SAMPLES:
    n_each = MAX_VAL_SAMPLES // 2
    val_df = pd.concat([
        val_df[val_df['label'] == 0].head(n_each),
        val_df[val_df['label'] == 1].head(n_each)
    ]).sample(frac=1.0, random_state=SEED).reset_index(drop=True)

train_ds = CIFAKEMetadataDataset(train_df, DATASET_ROOT, transform=RobustTransform(defense_strategy))
val_ds = CIFAKEMetadataDataset(val_df, DATASET_ROOT, transform=val_transform)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=NUM_WORKERS)
val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS)

print('train samples:', len(train_ds), 'val samples:', len(val_ds))

train samples: 4000 val samples: 1000

In [6]:
# Model + fine-tune

def build_model():
    model = models.resnet18(weights=None)
    model.fc = nn.Sequential(
        nn.Dropout(0.5),
        nn.Linear(model.fc.in_features, 256),
        nn.ReLU(),
        nn.Dropout(0.5),
        nn.Linear(256, 2)
    )
    return model


def evaluate_loader(model, loader):
    model.eval()
    total_loss = 0.0
    total = 0
    correct = 0
    criterion = nn.CrossEntropyLoss()
    with torch.no_grad():
        for x, y in loader:
            x, y = x.to(DEVICE), y.to(DEVICE)
            out = model(x)
            loss = criterion(out, y)
            total_loss += float(loss.item()) * x.size(0)
            preds = out.argmax(dim=1)
            total += y.numel()
            correct += int((preds == y).sum().item())
    return total_loss / max(total, 1), correct / max(total, 1)

base_model = build_model().to(DEVICE)
state_dict = torch.load(CHECKPOINT_PATH, map_location=DEVICE)
base_model.load_state_dict(state_dict)
base_model.eval()

robust_model = build_model().to(DEVICE)
robust_model.load_state_dict(state_dict)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(robust_model.parameters(), lr=3e-5, weight_decay=1e-4)

history = []
for epoch in range(1, EPOCHS + 1):
    robust_model.train()
    running_loss = 0.0
    total = 0
    correct = 0

    for x, y in tqdm(train_loader, desc=f'Epoch {epoch}/{EPOCHS}'):
        x, y = x.to(DEVICE), y.to(DEVICE)
        optimizer.zero_grad(set_to_none=True)
        out = robust_model(x)
        loss = criterion(out, y)
        loss.backward()
        optimizer.step()

        running_loss += float(loss.item()) * x.size(0)
        preds = out.argmax(dim=1)
        total += y.numel()
        correct += int((preds == y).sum().item())

    train_loss = running_loss / max(total, 1)
    train_acc = correct / max(total, 1)
    val_loss, val_acc = evaluate_loader(robust_model, val_loader)
    history.append({'epoch': epoch, 'train_loss': train_loss, 'train_acc': train_acc, 'val_loss': val_loss, 'val_acc': val_acc})
    print(f'Epoch {epoch}: train_loss={train_loss:.4f}, train_acc={train_acc:.4f}, val_loss={val_loss:.4f}, val_acc={val_acc:.4f}')

torch.save(robust_model.state_dict(), ROBUST_MODEL_PATH)
print('Saved:', ROBUST_MODEL_PATH)
pd.DataFrame(history)

Epoch 1/3:   0%|          | 0/125 [00:00<?, ?it/s]

Epoch 1/3:   1%|          | 1/125 [00:03<07:52,  3.81s/it]

Epoch 1/3:   2%|▏         | 2/125 [00:07<07:34,  3.70s/it]

Epoch 1/3:   2%|▏         | 3/125 [00:10<07:04,  3.48s/it]

Epoch 1/3:   3%|▎         | 4/125 [00:13<06:15,  3.10s/it]

Epoch 1/3:   4%|▍         | 5/125 [00:15<05:51,  2.93s/it]

Epoch 1/3:   5%|▍         | 6/125 [00:20<07:00,  3.54s/it]

Epoch 1/3:   6%|▌         | 7/125 [00:25<07:59,  4.06s/it]

Epoch 1/3:   6%|▋         | 8/125 [00:28<06:59,  3.59s/it]

Epoch 1/3:   7%|▋         | 9/125 [00:30<06:11,  3.20s/it]

Epoch 1/3:   8%|▊         | 10/125 [00:33<06:08,  3.20s/it]

Epoch 1/3:   9%|▉         | 11/125 [00:36<05:47,  3.05s/it]

Epoch 1/3:  10%|▉         | 12/125 [00:40<06:16,  3.33s/it]

Epoch 1/3:  10%|█         | 13/125 [00:43<05:53,  3.16s/it]

Epoch 1/3:  11%|█         | 14/125 [00:46<05:45,  3.12s/it]

Epoch 1/3:  12%|█▏        | 15/125 [00:49<05:47,  3.16s/it]

Epoch 1/3:  13%|█▎        | 16/125 [00:52<05:37,  3.10s/it]

Epoch 1/3:  14%|█▎        | 17/125 [00:55<05:30,  3.06s/it]

Epoch 1/3:  14%|█▍        | 18/125 [00:57<05:10,  2.91s/it]

Epoch 1/3:  15%|█▌        | 19/125 [01:00<04:59,  2.82s/it]

Epoch 1/3:  16%|█▌        | 20/125 [01:02<04:40,  2.67s/it]

Epoch 1/3:  17%|█▋        | 21/125 [01:05<04:39,  2.69s/it]

Epoch 1/3:  18%|█▊        | 22/125 [01:08<04:31,  2.63s/it]

Epoch 1/3:  18%|█▊        | 23/125 [01:10<04:32,  2.67s/it]

Epoch 1/3:  19%|█▉        | 24/125 [01:13<04:22,  2.60s/it]

Epoch 1/3:  20%|██        | 25/125 [01:15<04:10,  2.50s/it]

Epoch 1/3:  21%|██        | 26/125 [01:18<04:08,  2.51s/it]

Epoch 1/3:  22%|██▏       | 27/125 [01:22<04:52,  2.99s/it]

Epoch 1/3:  22%|██▏       | 28/125 [01:24<04:33,  2.82s/it]

Epoch 1/3:  23%|██▎       | 29/125 [01:27<04:26,  2.78s/it]

Epoch 1/3:  24%|██▍       | 30/125 [01:30<04:22,  2.77s/it]

Epoch 1/3:  25%|██▍       | 31/125 [01:34<04:58,  3.17s/it]

Epoch 1/3:  26%|██▌       | 32/125 [01:37<04:59,  3.22s/it]

Epoch 1/3:  26%|██▋       | 33/125 [01:41<05:03,  3.30s/it]

Epoch 1/3:  27%|██▋       | 34/125 [01:43<04:42,  3.11s/it]

Epoch 1/3:  28%|██▊       | 35/125 [01:46<04:33,  3.04s/it]

Epoch 1/3:  29%|██▉       | 36/125 [01:49<04:34,  3.09s/it]

Epoch 1/3:  30%|██▉       | 37/125 [01:52<04:25,  3.01s/it]

Epoch 1/3:  30%|███       | 38/125 [01:55<04:18,  2.97s/it]

Epoch 1/3:  31%|███       | 39/125 [01:58<04:03,  2.84s/it]

Epoch 1/3:  32%|███▏      | 40/125 [02:00<03:52,  2.74s/it]

Epoch 1/3:  33%|███▎      | 41/125 [02:02<03:38,  2.60s/it]

Epoch 1/3:  34%|███▎      | 42/125 [02:05<03:34,  2.58s/it]

Epoch 1/3:  34%|███▍      | 43/125 [02:07<03:28,  2.55s/it]

Epoch 1/3:  35%|███▌      | 44/125 [02:11<03:48,  2.82s/it]

Epoch 1/3:  36%|███▌      | 45/125 [02:14<03:45,  2.82s/it]

Epoch 1/3:  37%|███▋      | 46/125 [02:16<03:42,  2.82s/it]

Epoch 1/3:  38%|███▊      | 47/125 [02:19<03:30,  2.70s/it]

Epoch 1/3:  38%|███▊      | 48/125 [02:21<03:21,  2.61s/it]

Epoch 1/3:  39%|███▉      | 49/125 [02:25<03:38,  2.88s/it]

Epoch 1/3:  40%|████      | 50/125 [02:28<03:53,  3.11s/it]

Epoch 1/3:  41%|████      | 51/125 [02:31<03:35,  2.91s/it]

Epoch 1/3:  42%|████▏     | 52/125 [02:33<03:20,  2.74s/it]

Epoch 1/3:  42%|████▏     | 53/125 [02:36<03:18,  2.76s/it]

Epoch 1/3:  43%|████▎     | 54/125 [02:39<03:21,  2.84s/it]

Epoch 1/3:  44%|████▍     | 55/125 [02:42<03:16,  2.80s/it]

Epoch 1/3:  45%|████▍     | 56/125 [02:45<03:26,  2.99s/it]

Epoch 1/3:  46%|████▌     | 57/125 [02:47<03:10,  2.80s/it]

Epoch 1/3:  46%|████▋     | 58/125 [02:51<03:12,  2.87s/it]

Epoch 1/3:  47%|████▋     | 59/125 [02:53<03:07,  2.84s/it]

Epoch 1/3:  48%|████▊     | 60/125 [02:56<03:00,  2.77s/it]

Epoch 1/3:  49%|████▉     | 61/125 [02:58<02:53,  2.71s/it]

Epoch 1/3:  50%|████▉     | 62/125 [03:01<02:43,  2.60s/it]

Epoch 1/3:  50%|█████     | 63/125 [03:03<02:35,  2.50s/it]

Epoch 1/3:  51%|█████     | 64/125 [03:06<02:35,  2.56s/it]

Epoch 1/3:  52%|█████▏    | 65/125 [03:09<02:37,  2.62s/it]

Epoch 1/3:  53%|█████▎    | 66/125 [03:11<02:28,  2.52s/it]

Epoch 1/3:  54%|█████▎    | 67/125 [03:14<02:30,  2.59s/it]

Epoch 1/3:  54%|█████▍    | 68/125 [03:17<02:42,  2.85s/it]

Epoch 1/3:  55%|█████▌    | 69/125 [03:20<02:40,  2.87s/it]

Epoch 1/3:  56%|█████▌    | 70/125 [03:22<02:29,  2.72s/it]

Epoch 1/3:  57%|█████▋    | 71/125 [03:25<02:25,  2.70s/it]

Epoch 1/3:  58%|█████▊    | 72/125 [03:27<02:19,  2.63s/it]

Epoch 1/3:  58%|█████▊    | 73/125 [03:30<02:13,  2.57s/it]

Epoch 1/3:  59%|█████▉    | 74/125 [03:32<02:10,  2.55s/it]

Epoch 1/3:  60%|██████    | 75/125 [03:35<02:05,  2.51s/it]

Epoch 1/3:  61%|██████    | 76/125 [03:37<02:05,  2.55s/it]

Epoch 1/3:  62%|██████▏   | 77/125 [03:40<02:03,  2.58s/it]

Epoch 1/3:  62%|██████▏   | 78/125 [03:43<02:01,  2.59s/it]

Epoch 1/3:  63%|██████▎   | 79/125 [03:45<01:58,  2.58s/it]

Epoch 1/3:  64%|██████▍   | 80/125 [03:48<01:58,  2.64s/it]

Epoch 1/3:  65%|██████▍   | 81/125 [03:51<02:00,  2.74s/it]

Epoch 1/3:  66%|██████▌   | 82/125 [03:53<01:53,  2.65s/it]

Epoch 1/3:  66%|██████▋   | 83/125 [03:56<01:47,  2.56s/it]

Epoch 1/3:  67%|██████▋   | 84/125 [03:58<01:45,  2.57s/it]

Epoch 1/3:  68%|██████▊   | 85/125 [04:01<01:40,  2.52s/it]

Epoch 1/3:  69%|██████▉   | 86/125 [04:03<01:36,  2.49s/it]

Epoch 1/3:  70%|██████▉   | 87/125 [04:06<01:37,  2.57s/it]

Epoch 1/3:  70%|███████   | 88/125 [04:09<01:39,  2.68s/it]

Epoch 1/3:  71%|███████   | 89/125 [04:11<01:34,  2.64s/it]

Epoch 1/3:  72%|███████▏  | 90/125 [04:14<01:28,  2.54s/it]

Epoch 1/3:  73%|███████▎  | 91/125 [04:16<01:24,  2.48s/it]

Epoch 1/3:  74%|███████▎  | 92/125 [04:19<01:21,  2.46s/it]

Epoch 1/3:  74%|███████▍  | 93/125 [04:21<01:17,  2.42s/it]

Epoch 1/3:  75%|███████▌  | 94/125 [04:23<01:14,  2.40s/it]

Epoch 1/3:  76%|███████▌  | 95/125 [04:26<01:15,  2.52s/it]

Epoch 1/3:  77%|███████▋  | 96/125 [04:29<01:13,  2.55s/it]

Epoch 1/3:  78%|███████▊  | 97/125 [04:31<01:09,  2.47s/it]

Epoch 1/3:  78%|███████▊  | 98/125 [04:33<01:04,  2.40s/it]

Epoch 1/3:  79%|███████▉  | 99/125 [04:35<01:00,  2.34s/it]

Epoch 1/3:  80%|████████  | 100/125 [04:38<00:58,  2.35s/it]

Epoch 1/3:  81%|████████  | 101/125 [04:40<00:56,  2.34s/it]

Epoch 1/3:  82%|████████▏ | 102/125 [04:42<00:53,  2.33s/it]

Epoch 1/3:  82%|████████▏ | 103/125 [04:45<00:51,  2.34s/it]

Epoch 1/3:  83%|████████▎ | 104/125 [04:47<00:49,  2.37s/it]

Epoch 1/3:  84%|████████▍ | 105/125 [04:49<00:47,  2.37s/it]

Epoch 1/3:  85%|████████▍ | 106/125 [04:52<00:44,  2.37s/it]

Epoch 1/3:  86%|████████▌ | 107/125 [04:54<00:42,  2.34s/it]

Epoch 1/3:  86%|████████▋ | 108/125 [04:57<00:40,  2.38s/it]

Epoch 1/3:  87%|████████▋ | 109/125 [04:59<00:37,  2.32s/it]

Epoch 1/3:  88%|████████▊ | 110/125 [05:01<00:35,  2.36s/it]

Epoch 1/3:  89%|████████▉ | 111/125 [05:04<00:32,  2.34s/it]

Epoch 1/3:  90%|████████▉ | 112/125 [05:06<00:30,  2.38s/it]

Epoch 1/3:  90%|█████████ | 113/125 [05:09<00:30,  2.58s/it]

Epoch 1/3:  91%|█████████ | 114/125 [05:12<00:28,  2.59s/it]

Epoch 1/3:  92%|█████████▏| 115/125 [05:14<00:25,  2.57s/it]

Epoch 1/3:  93%|█████████▎| 116/125 [05:18<00:26,  2.95s/it]

Epoch 1/3:  94%|█████████▎| 117/125 [05:21<00:23,  2.91s/it]

Epoch 1/3:  94%|█████████▍| 118/125 [05:23<00:19,  2.79s/it]

Epoch 1/3:  95%|█████████▌| 119/125 [05:26<00:17,  2.88s/it]

Epoch 1/3:  96%|█████████▌| 120/125 [05:29<00:13,  2.74s/it]

Epoch 1/3:  97%|█████████▋| 121/125 [05:32<00:11,  2.85s/it]

Epoch 1/3:  98%|█████████▊| 122/125 [05:34<00:08,  2.72s/it]

Epoch 1/3:  98%|█████████▊| 123/125 [05:37<00:05,  2.63s/it]

Epoch 1/3:  99%|█████████▉| 124/125 [05:40<00:02,  2.68s/it]

Epoch 1/3: 100%|██████████| 125/125 [05:42<00:00,  2.56s/it]

Epoch 1/3: 100%|██████████| 125/125 [05:42<00:00,  2.74s/it]

Epoch 1: train_loss=0.5030, train_acc=0.7500, val_loss=0.3074, val_acc=0.8700

Epoch 2/3:   0%|          | 0/125 [00:00<?, ?it/s]

Epoch 2/3:   1%|          | 1/125 [00:02<05:09,  2.50s/it]

Epoch 2/3:   2%|▏         | 2/125 [00:05<05:20,  2.61s/it]

Epoch 2/3:   2%|▏         | 3/125 [00:07<05:00,  2.46s/it]

Epoch 2/3:   3%|▎         | 4/125 [00:09<04:57,  2.46s/it]

Epoch 2/3:   4%|▍         | 5/125 [00:13<05:39,  2.83s/it]

Epoch 2/3:   5%|▍         | 6/125 [00:16<05:27,  2.75s/it]

Epoch 2/3:   6%|▌         | 7/125 [00:18<05:24,  2.75s/it]

Epoch 2/3:   6%|▋         | 8/125 [00:21<05:39,  2.90s/it]

Epoch 2/3:   7%|▋         | 9/125 [00:24<05:26,  2.81s/it]

Epoch 2/3:   8%|▊         | 10/125 [00:27<05:09,  2.69s/it]

Epoch 2/3:   9%|▉         | 11/125 [00:29<04:58,  2.62s/it]

Epoch 2/3:  10%|▉         | 12/125 [00:31<04:46,  2.53s/it]

Epoch 2/3:  10%|█         | 13/125 [00:34<04:57,  2.65s/it]

Epoch 2/3:  11%|█         | 14/125 [00:37<04:54,  2.66s/it]

Epoch 2/3:  12%|█▏        | 15/125 [00:40<05:02,  2.75s/it]

Epoch 2/3:  13%|█▎        | 16/125 [00:43<05:01,  2.77s/it]

Epoch 2/3:  14%|█▎        | 17/125 [00:46<05:31,  3.07s/it]

Epoch 2/3:  14%|█▍        | 18/125 [00:49<05:19,  2.99s/it]

Epoch 2/3:  15%|█▌        | 19/125 [00:52<05:16,  2.99s/it]

Epoch 2/3:  16%|█▌        | 20/125 [00:55<05:09,  2.95s/it]

Epoch 2/3:  17%|█▋        | 21/125 [00:58<05:02,  2.91s/it]

Epoch 2/3:  18%|█▊        | 22/125 [01:00<04:42,  2.74s/it]

Epoch 2/3:  18%|█▊        | 23/125 [01:03<04:27,  2.62s/it]

Epoch 2/3:  19%|█▉        | 24/125 [01:05<04:18,  2.56s/it]

Epoch 2/3:  20%|██        | 25/125 [01:08<04:17,  2.58s/it]

Epoch 2/3:  21%|██        | 26/125 [01:11<04:26,  2.70s/it]

Epoch 2/3:  22%|██▏       | 27/125 [01:13<04:20,  2.66s/it]

Epoch 2/3:  22%|██▏       | 28/125 [01:16<04:21,  2.70s/it]

Epoch 2/3:  23%|██▎       | 29/125 [01:18<04:13,  2.64s/it]

Epoch 2/3:  24%|██▍       | 30/125 [01:21<04:19,  2.73s/it]

Epoch 2/3:  25%|██▍       | 31/125 [01:25<04:39,  2.98s/it]

Epoch 2/3:  26%|██▌       | 32/125 [01:28<04:36,  2.98s/it]

Epoch 2/3:  26%|██▋       | 33/125 [01:31<04:31,  2.95s/it]

Epoch 2/3:  27%|██▋       | 34/125 [01:34<04:20,  2.86s/it]

Epoch 2/3:  28%|██▊       | 35/125 [01:36<04:07,  2.75s/it]

Epoch 2/3:  29%|██▉       | 36/125 [01:39<03:59,  2.69s/it]

Epoch 2/3:  30%|██▉       | 37/125 [01:41<03:45,  2.56s/it]

Epoch 2/3:  30%|███       | 38/125 [01:43<03:36,  2.49s/it]

Epoch 2/3:  31%|███       | 39/125 [01:45<03:30,  2.45s/it]

Epoch 2/3:  32%|███▏      | 40/125 [01:48<03:26,  2.43s/it]

Epoch 2/3:  33%|███▎      | 41/125 [01:50<03:21,  2.40s/it]

Epoch 2/3:  34%|███▎      | 42/125 [01:53<03:20,  2.42s/it]

Epoch 2/3:  34%|███▍      | 43/125 [01:56<03:51,  2.82s/it]

Epoch 2/3:  35%|███▌      | 44/125 [01:59<03:42,  2.75s/it]

Epoch 2/3:  36%|███▌      | 45/125 [02:01<03:31,  2.64s/it]

Epoch 2/3:  37%|███▋      | 46/125 [02:04<03:33,  2.70s/it]

Epoch 2/3:  38%|███▊      | 47/125 [02:07<03:27,  2.66s/it]

Epoch 2/3:  38%|███▊      | 48/125 [02:09<03:23,  2.64s/it]

Epoch 2/3:  39%|███▉      | 49/125 [02:12<03:17,  2.60s/it]

Epoch 2/3:  40%|████      | 50/125 [02:15<03:19,  2.66s/it]

Epoch 2/3:  41%|████      | 51/125 [02:17<03:09,  2.55s/it]

Epoch 2/3:  42%|████▏     | 52/125 [02:19<03:01,  2.49s/it]

Epoch 2/3:  42%|████▏     | 53/125 [02:22<02:53,  2.41s/it]

Epoch 2/3:  43%|████▎     | 54/125 [02:24<02:47,  2.37s/it]

Epoch 2/3:  44%|████▍     | 55/125 [02:26<02:49,  2.42s/it]

Epoch 2/3:  45%|████▍     | 56/125 [02:29<02:45,  2.39s/it]

Epoch 2/3:  46%|████▌     | 57/125 [02:31<02:40,  2.36s/it]

Epoch 2/3:  46%|████▋     | 58/125 [02:33<02:36,  2.33s/it]

Epoch 2/3:  47%|████▋     | 59/125 [02:36<02:33,  2.33s/it]

Epoch 2/3:  48%|████▊     | 60/125 [02:38<02:35,  2.39s/it]

Epoch 2/3:  49%|████▉     | 61/125 [02:41<02:35,  2.42s/it]

Epoch 2/3:  50%|████▉     | 62/125 [02:43<02:35,  2.46s/it]

Epoch 2/3:  50%|█████     | 63/125 [02:46<02:40,  2.58s/it]

Epoch 2/3:  51%|█████     | 64/125 [02:48<02:32,  2.49s/it]

Epoch 2/3:  52%|█████▏    | 65/125 [02:51<02:27,  2.46s/it]

Epoch 2/3:  53%|█████▎    | 66/125 [02:53<02:24,  2.46s/it]

Epoch 2/3:  54%|█████▎    | 67/125 [02:56<02:31,  2.61s/it]

Epoch 2/3:  54%|█████▍    | 68/125 [02:59<02:35,  2.73s/it]

Epoch 2/3:  55%|█████▌    | 69/125 [03:02<02:34,  2.77s/it]

Epoch 2/3:  56%|█████▌    | 70/125 [03:06<02:52,  3.13s/it]

Epoch 2/3:  57%|█████▋    | 71/125 [03:09<02:42,  3.01s/it]

Epoch 2/3:  58%|█████▊    | 72/125 [03:11<02:34,  2.91s/it]

Epoch 2/3:  58%|█████▊    | 73/125 [03:16<03:01,  3.48s/it]

Epoch 2/3:  59%|█████▉    | 74/125 [03:21<03:23,  3.99s/it]

Epoch 2/3:  60%|██████    | 75/125 [03:25<03:11,  3.82s/it]

Epoch 2/3:  61%|██████    | 76/125 [03:28<02:57,  3.63s/it]

Epoch 2/3:  62%|██████▏   | 77/125 [03:31<02:38,  3.31s/it]

Epoch 2/3:  62%|██████▏   | 78/125 [03:33<02:19,  2.98s/it]

Epoch 2/3:  63%|██████▎   | 79/125 [03:35<02:06,  2.75s/it]

Epoch 2/3:  64%|██████▍   | 80/125 [03:37<01:59,  2.65s/it]

Epoch 2/3:  65%|██████▍   | 81/125 [03:40<02:02,  2.80s/it]

Epoch 2/3:  66%|██████▌   | 82/125 [03:43<01:56,  2.71s/it]

Epoch 2/3:  66%|██████▋   | 83/125 [03:46<02:00,  2.86s/it]

Epoch 2/3:  67%|██████▋   | 84/125 [03:49<01:51,  2.73s/it]

Epoch 2/3:  68%|██████▊   | 85/125 [03:51<01:44,  2.62s/it]

Epoch 2/3:  69%|██████▉   | 86/125 [03:54<01:42,  2.64s/it]

Epoch 2/3:  70%|██████▉   | 87/125 [03:57<01:46,  2.80s/it]

Epoch 2/3:  70%|███████   | 88/125 [04:00<01:44,  2.84s/it]

Epoch 2/3:  71%|███████   | 89/125 [04:03<01:42,  2.84s/it]

Epoch 2/3:  72%|███████▏  | 90/125 [04:05<01:35,  2.72s/it]

Epoch 2/3:  73%|███████▎  | 91/125 [04:07<01:29,  2.62s/it]

Epoch 2/3:  74%|███████▎  | 92/125 [04:10<01:24,  2.56s/it]

Epoch 2/3:  74%|███████▍  | 93/125 [04:12<01:19,  2.49s/it]

Epoch 2/3:  75%|███████▌  | 94/125 [04:15<01:18,  2.52s/it]

Epoch 2/3:  76%|███████▌  | 95/125 [04:17<01:13,  2.47s/it]

Epoch 2/3:  77%|███████▋  | 96/125 [04:21<01:20,  2.77s/it]

Epoch 2/3:  78%|███████▊  | 97/125 [04:23<01:15,  2.68s/it]

Epoch 2/3:  78%|███████▊  | 98/125 [04:25<01:09,  2.59s/it]

Epoch 2/3:  79%|███████▉  | 99/125 [04:28<01:10,  2.69s/it]

Epoch 2/3:  80%|████████  | 100/125 [04:31<01:06,  2.68s/it]

Epoch 2/3:  81%|████████  | 101/125 [04:33<01:02,  2.61s/it]

Epoch 2/3:  82%|████████▏ | 102/125 [04:36<00:59,  2.59s/it]

Epoch 2/3:  82%|████████▏ | 103/125 [04:39<01:01,  2.80s/it]

Epoch 2/3:  83%|████████▎ | 104/125 [04:42<00:55,  2.64s/it]

Epoch 2/3:  84%|████████▍ | 105/125 [04:44<00:54,  2.72s/it]

Epoch 2/3:  85%|████████▍ | 106/125 [04:47<00:49,  2.62s/it]

Epoch 2/3:  86%|████████▌ | 107/125 [04:49<00:45,  2.51s/it]

Epoch 2/3:  86%|████████▋ | 108/125 [04:51<00:41,  2.45s/it]

Epoch 2/3:  87%|████████▋ | 109/125 [04:54<00:40,  2.52s/it]

Epoch 2/3:  88%|████████▊ | 110/125 [04:57<00:39,  2.61s/it]

Epoch 2/3:  89%|████████▉ | 111/125 [05:00<00:36,  2.62s/it]

Epoch 2/3:  90%|████████▉ | 112/125 [05:02<00:33,  2.54s/it]

Epoch 2/3:  90%|█████████ | 113/125 [05:04<00:30,  2.51s/it]

Epoch 2/3:  91%|█████████ | 114/125 [05:08<00:30,  2.80s/it]

Epoch 2/3:  92%|█████████▏| 115/125 [05:10<00:27,  2.71s/it]

Epoch 2/3:  93%|█████████▎| 116/125 [05:13<00:25,  2.84s/it]

Epoch 2/3:  94%|█████████▎| 117/125 [05:16<00:21,  2.72s/it]

Epoch 2/3:  94%|█████████▍| 118/125 [05:18<00:18,  2.60s/it]

Epoch 2/3:  95%|█████████▌| 119/125 [05:21<00:15,  2.51s/it]

Epoch 2/3:  96%|█████████▌| 120/125 [05:23<00:12,  2.45s/it]

Epoch 2/3:  97%|█████████▋| 121/125 [05:25<00:09,  2.38s/it]

Epoch 2/3:  98%|█████████▊| 122/125 [05:27<00:07,  2.37s/it]

Epoch 2/3:  98%|█████████▊| 123/125 [05:30<00:04,  2.37s/it]

Epoch 2/3:  99%|█████████▉| 124/125 [05:32<00:02,  2.32s/it]

Epoch 2/3: 100%|██████████| 125/125 [05:34<00:00,  2.30s/it]

Epoch 2/3: 100%|██████████| 125/125 [05:34<00:00,  2.68s/it]

Epoch 2: train_loss=0.2825, train_acc=0.8872, val_loss=0.2256, val_acc=0.9030

Epoch 3/3:   0%|          | 0/125 [00:00<?, ?it/s]

Epoch 3/3:   1%|          | 1/125 [00:02<05:27,  2.64s/it]

Epoch 3/3:   2%|▏         | 2/125 [00:05<05:11,  2.53s/it]

Epoch 3/3:   2%|▏         | 3/125 [00:07<05:02,  2.48s/it]

Epoch 3/3:   3%|▎         | 4/125 [00:10<05:08,  2.55s/it]

Epoch 3/3:   4%|▍         | 5/125 [00:12<05:05,  2.55s/it]

Epoch 3/3:   5%|▍         | 6/125 [00:15<04:59,  2.52s/it]

Epoch 3/3:   6%|▌         | 7/125 [00:17<04:48,  2.45s/it]

Epoch 3/3:   6%|▋         | 8/125 [00:19<04:40,  2.39s/it]

Epoch 3/3:   7%|▋         | 9/125 [00:22<04:40,  2.42s/it]

Epoch 3/3:   8%|▊         | 10/125 [00:24<04:40,  2.44s/it]

Epoch 3/3:   9%|▉         | 11/125 [00:27<04:35,  2.42s/it]

Epoch 3/3:  10%|▉         | 12/125 [00:29<04:32,  2.41s/it]

Epoch 3/3:  10%|█         | 13/125 [00:31<04:29,  2.40s/it]

Epoch 3/3:  11%|█         | 14/125 [00:34<04:25,  2.40s/it]

Epoch 3/3:  12%|█▏        | 15/125 [00:36<04:32,  2.48s/it]

Epoch 3/3:  13%|█▎        | 16/125 [00:39<04:24,  2.43s/it]

Epoch 3/3:  14%|█▎        | 17/125 [00:41<04:17,  2.39s/it]

Epoch 3/3:  14%|█▍        | 18/125 [00:43<04:14,  2.38s/it]

Epoch 3/3:  15%|█▌        | 19/125 [00:48<05:19,  3.02s/it]

Epoch 3/3:  16%|█▌        | 20/125 [00:51<05:19,  3.04s/it]

Epoch 3/3:  17%|█▋        | 21/125 [00:54<05:01,  2.90s/it]

Epoch 3/3:  18%|█▊        | 22/125 [00:57<05:07,  2.99s/it]

Epoch 3/3:  18%|█▊        | 23/125 [00:59<04:46,  2.81s/it]

Epoch 3/3:  19%|█▉        | 24/125 [01:01<04:29,  2.66s/it]

Epoch 3/3:  20%|██        | 25/125 [01:04<04:32,  2.72s/it]

Epoch 3/3:  21%|██        | 26/125 [01:07<04:28,  2.71s/it]

Epoch 3/3:  22%|██▏       | 27/125 [01:10<04:20,  2.66s/it]

Epoch 3/3:  22%|██▏       | 28/125 [01:12<04:21,  2.70s/it]

Epoch 3/3:  23%|██▎       | 29/125 [01:15<04:22,  2.73s/it]

Epoch 3/3:  24%|██▍       | 30/125 [01:18<04:14,  2.67s/it]

Epoch 3/3:  25%|██▍       | 31/125 [01:20<04:02,  2.58s/it]

Epoch 3/3:  26%|██▌       | 32/125 [01:23<04:00,  2.59s/it]

Epoch 3/3:  26%|██▋       | 33/125 [01:25<03:57,  2.58s/it]

Epoch 3/3:  27%|██▋       | 34/125 [01:28<03:52,  2.56s/it]

Epoch 3/3:  28%|██▊       | 35/125 [01:30<03:48,  2.54s/it]

Epoch 3/3:  29%|██▉       | 36/125 [01:33<03:47,  2.55s/it]

Epoch 3/3:  30%|██▉       | 37/125 [01:35<03:40,  2.51s/it]

Epoch 3/3:  30%|███       | 38/125 [01:38<03:35,  2.48s/it]

Epoch 3/3:  31%|███       | 39/125 [01:40<03:28,  2.42s/it]

Epoch 3/3:  32%|███▏      | 40/125 [01:42<03:23,  2.39s/it]

Epoch 3/3:  33%|███▎      | 41/125 [01:45<03:20,  2.38s/it]

Epoch 3/3:  34%|███▎      | 42/125 [01:47<03:18,  2.39s/it]

Epoch 3/3:  34%|███▍      | 43/125 [01:49<03:12,  2.34s/it]

Epoch 3/3:  35%|███▌      | 44/125 [01:51<03:07,  2.31s/it]

Epoch 3/3:  36%|███▌      | 45/125 [01:54<03:12,  2.41s/it]

Epoch 3/3:  37%|███▋      | 46/125 [01:57<03:19,  2.52s/it]

Epoch 3/3:  38%|███▊      | 47/125 [01:59<03:10,  2.44s/it]

Epoch 3/3:  38%|███▊      | 48/125 [02:02<03:16,  2.55s/it]

Epoch 3/3:  39%|███▉      | 49/125 [02:04<03:09,  2.49s/it]

Epoch 3/3:  40%|████      | 50/125 [02:07<03:05,  2.47s/it]

Epoch 3/3:  41%|████      | 51/125 [02:09<03:00,  2.43s/it]

Epoch 3/3:  42%|████▏     | 52/125 [02:12<03:04,  2.53s/it]

Epoch 3/3:  42%|████▏     | 53/125 [02:14<02:56,  2.45s/it]

Epoch 3/3:  43%|████▎     | 54/125 [02:16<02:49,  2.39s/it]

Epoch 3/3:  44%|████▍     | 55/125 [02:19<02:45,  2.37s/it]

Epoch 3/3:  45%|████▍     | 56/125 [02:21<02:40,  2.32s/it]

Epoch 3/3:  46%|████▌     | 57/125 [02:23<02:37,  2.31s/it]

Epoch 3/3:  46%|████▋     | 58/125 [02:26<02:36,  2.34s/it]

Epoch 3/3:  47%|████▋     | 59/125 [02:28<02:32,  2.31s/it]

Epoch 3/3:  48%|████▊     | 60/125 [02:30<02:28,  2.28s/it]

Epoch 3/3:  49%|████▉     | 61/125 [02:32<02:27,  2.31s/it]

Epoch 3/3:  50%|████▉     | 62/125 [02:35<02:29,  2.38s/it]

Epoch 3/3:  50%|█████     | 63/125 [02:37<02:29,  2.41s/it]

Epoch 3/3:  51%|█████     | 64/125 [02:40<02:24,  2.38s/it]

Epoch 3/3:  52%|█████▏    | 65/125 [02:42<02:22,  2.37s/it]

Epoch 3/3:  53%|█████▎    | 66/125 [02:44<02:17,  2.34s/it]

Epoch 3/3:  54%|█████▎    | 67/125 [02:47<02:13,  2.31s/it]

Epoch 3/3:  54%|█████▍    | 68/125 [02:49<02:10,  2.28s/it]

Epoch 3/3:  55%|█████▌    | 69/125 [02:51<02:07,  2.28s/it]

Epoch 3/3:  56%|█████▌    | 70/125 [02:54<02:16,  2.48s/it]

Epoch 3/3:  57%|█████▋    | 71/125 [02:57<02:16,  2.52s/it]

Epoch 3/3:  58%|█████▊    | 72/125 [02:59<02:10,  2.46s/it]

Epoch 3/3:  58%|█████▊    | 73/125 [03:01<02:04,  2.39s/it]

Epoch 3/3:  59%|█████▉    | 74/125 [03:04<02:08,  2.52s/it]

Epoch 3/3:  60%|██████    | 75/125 [03:06<02:04,  2.49s/it]

Epoch 3/3:  61%|██████    | 76/125 [03:09<02:01,  2.47s/it]

Epoch 3/3:  62%|██████▏   | 77/125 [03:12<02:02,  2.55s/it]

Epoch 3/3:  62%|██████▏   | 78/125 [03:14<01:56,  2.48s/it]

Epoch 3/3:  63%|██████▎   | 79/125 [03:16<01:52,  2.44s/it]

Epoch 3/3:  64%|██████▍   | 80/125 [03:19<01:50,  2.45s/it]

Epoch 3/3:  65%|██████▍   | 81/125 [03:21<01:45,  2.40s/it]

Epoch 3/3:  66%|██████▌   | 82/125 [03:23<01:44,  2.42s/it]

Epoch 3/3:  66%|██████▋   | 83/125 [03:26<01:40,  2.39s/it]

Epoch 3/3:  67%|██████▋   | 84/125 [03:28<01:36,  2.35s/it]

Epoch 3/3:  68%|██████▊   | 85/125 [03:30<01:33,  2.33s/it]

Epoch 3/3:  69%|██████▉   | 86/125 [03:33<01:31,  2.33s/it]

Epoch 3/3:  70%|██████▉   | 87/125 [03:35<01:27,  2.32s/it]

Epoch 3/3:  70%|███████   | 88/125 [03:37<01:26,  2.34s/it]

Epoch 3/3:  71%|███████   | 89/125 [03:40<01:22,  2.30s/it]

Epoch 3/3:  72%|███████▏  | 90/125 [03:42<01:19,  2.27s/it]

Epoch 3/3:  73%|███████▎  | 91/125 [03:44<01:17,  2.27s/it]

Epoch 3/3:  74%|███████▎  | 92/125 [03:46<01:14,  2.27s/it]

Epoch 3/3:  74%|███████▍  | 93/125 [03:48<01:12,  2.25s/it]

Epoch 3/3:  75%|███████▌  | 94/125 [03:51<01:09,  2.23s/it]

Epoch 3/3:  76%|███████▌  | 95/125 [03:53<01:07,  2.24s/it]

Epoch 3/3:  77%|███████▋  | 96/125 [03:56<01:09,  2.38s/it]

Epoch 3/3:  78%|███████▊  | 97/125 [03:58<01:06,  2.37s/it]

Epoch 3/3:  78%|███████▊  | 98/125 [04:00<01:02,  2.33s/it]

Epoch 3/3:  79%|███████▉  | 99/125 [04:03<01:00,  2.33s/it]

Epoch 3/3:  80%|████████  | 100/125 [04:05<00:58,  2.33s/it]

Epoch 3/3:  81%|████████  | 101/125 [04:08<00:58,  2.45s/it]

Epoch 3/3:  82%|████████▏ | 102/125 [04:10<00:54,  2.39s/it]

Epoch 3/3:  82%|████████▏ | 103/125 [04:14<01:02,  2.83s/it]

Epoch 3/3:  83%|████████▎ | 104/125 [04:16<00:57,  2.73s/it]

Epoch 3/3:  84%|████████▍ | 105/125 [04:18<00:51,  2.58s/it]

Epoch 3/3:  85%|████████▍ | 106/125 [04:21<00:47,  2.51s/it]

Epoch 3/3:  86%|████████▌ | 107/125 [04:25<00:53,  2.96s/it]

Epoch 3/3:  86%|████████▋ | 108/125 [04:27<00:46,  2.75s/it]

Epoch 3/3:  87%|████████▋ | 109/125 [04:29<00:40,  2.54s/it]

Epoch 3/3:  88%|████████▊ | 110/125 [04:31<00:36,  2.41s/it]

Epoch 3/3:  89%|████████▉ | 111/125 [04:34<00:34,  2.45s/it]

Epoch 3/3:  90%|████████▉ | 112/125 [04:36<00:31,  2.40s/it]

Epoch 3/3:  90%|█████████ | 113/125 [04:38<00:28,  2.37s/it]

Epoch 3/3:  91%|█████████ | 114/125 [04:40<00:25,  2.28s/it]

Epoch 3/3:  92%|█████████▏| 115/125 [04:43<00:22,  2.27s/it]

Epoch 3/3:  93%|█████████▎| 116/125 [04:45<00:20,  2.26s/it]

Epoch 3/3:  94%|█████████▎| 117/125 [04:47<00:17,  2.25s/it]

Epoch 3/3:  94%|█████████▍| 118/125 [04:49<00:15,  2.23s/it]

Epoch 3/3:  95%|█████████▌| 119/125 [04:51<00:13,  2.17s/it]

Epoch 3/3:  96%|█████████▌| 120/125 [04:54<00:10,  2.19s/it]

Epoch 3/3:  97%|█████████▋| 121/125 [04:56<00:09,  2.28s/it]

Epoch 3/3:  98%|█████████▊| 122/125 [04:58<00:06,  2.29s/it]

Epoch 3/3:  98%|█████████▊| 123/125 [05:01<00:04,  2.28s/it]

Epoch 3/3:  99%|█████████▉| 124/125 [05:03<00:02,  2.27s/it]

Epoch 3/3: 100%|██████████| 125/125 [05:05<00:00,  2.25s/it]

Epoch 3/3: 100%|██████████| 125/125 [05:05<00:00,  2.44s/it]

Epoch 3: train_loss=0.2040, train_acc=0.9215, val_loss=0.1842, val_acc=0.9210

Saved: /Users/arulkevin/Desktop/psg_hackathon/Feb-2026-Hackathon/Phase 3/outputs/robust_model_prototype.pt

   epoch  train_loss  train_acc  val_loss  val_acc
0      1    0.503033    0.75000  0.307403    0.870
1      2    0.282523    0.88725  0.225576    0.903
2      3    0.203999    0.92150  0.184196    0.921

In [7]:
# Attack functions from M1

def apply_blur(image_np, radius):
    pil = Image.fromarray(image_np)
    return np.array(pil.filter(ImageFilter.GaussianBlur(radius=float(radius))))


def apply_frequency_mask(image_np, strength):
    img_float = image_np.astype(np.float32) / 255.0
    dft = np.fft.fft2(img_float, axes=(0, 1))
    dft_shift = np.fft.fftshift(dft, axes=(0, 1))

    h, w, _ = img_float.shape
    mask = np.ones((h, w, 3), np.float32)
    center_h, center_w = h // 2, w // 2
    radius = int(min(h, w) * float(strength))
    mask[center_h-radius:center_h+radius, center_w-radius:center_w+radius] *= 0.5

    dft_shift = dft_shift * mask
    f_ishift = np.fft.ifftshift(dft_shift, axes=(0, 1))
    img_back = np.fft.ifft2(f_ishift, axes=(0, 1))
    img_back = np.abs(img_back)
    img_back = np.clip(img_back, 0, 1)
    return (img_back * 255).astype(np.uint8)


def apply_noise(image_np, sigma, rng):
    noise = rng.normal(0, sigma * 255, image_np.shape)
    noisy = image_np + noise
    return np.clip(noisy, 0, 255).astype(np.uint8)


def apply_brightness(image_np, factor):
    bright = image_np.astype(np.float32) * factor
    return np.clip(bright, 0, 255).astype(np.uint8)


def to_model_tensor(img_np):
    pil = Image.fromarray(img_np)
    x = val_transform(pil).unsqueeze(0).to(DEVICE)
    return x


def predict_details(model, img_np):
    x = to_model_tensor(img_np)
    with torch.no_grad():
        out = model(x)
        probs = F.softmax(out, dim=1)[0]
    pred = int(torch.argmax(probs).item())
    conf = float(probs[pred].item())
    p_fake = float(probs[1].item())
    return pred, conf, p_fake

In [8]:
# Re-run Strategy A/B attacks on same sample set as M1
m1_df = pd.read_csv(M1_RESULTS_PATH)
sample_map = m1_df[['sample_id', 'true_label']].drop_duplicates().reset_index(drop=True)

blur_levels = [0.3, 0.5, 0.8, 1.0]
freq_levels = [0.05, 0.1, 0.15]
noise_levels = [0.01, 0.02, 0.03, 0.05]
brightness_levels = [1.02, 1.05, 1.08]


def eval_model_under_attacks(model, out_path):
    rows = []
    model.eval()

    for _, r in tqdm(sample_map.iterrows(), total=len(sample_map), desc='Attacking'):
        sid = str(r['sample_id'])
        label = str(r['true_label'])
        img_path = DATASET_ROOT / 'test' / label / sid
        if not img_path.exists():
            continue

        image = Image.open(img_path).convert('RGB')
        image_np = np.array(image)

        orig_pred, orig_conf, orig_pfake = predict_details(model, image_np)
        rows.append({'sample_id': sid, 'true_label': label, 'strategy': 'original', 'stage': 'original', 'parameter': 0.0, 'confidence': orig_conf, 'p_fake': orig_pfake, 'flipped': False})

        for blur in blur_levels:
            adv = apply_blur(image_np, blur)
            pred, conf, pfake = predict_details(model, adv)
            rows.append({'sample_id': sid, 'true_label': label, 'strategy': 'A_blur', 'stage': f'blur_{blur}', 'parameter': blur, 'confidence': conf, 'p_fake': pfake, 'flipped': pred != orig_pred})

        for freq in freq_levels:
            adv = apply_blur(image_np, 0.5)
            adv = apply_frequency_mask(adv, freq)
            pred, conf, pfake = predict_details(model, adv)
            rows.append({'sample_id': sid, 'true_label': label, 'strategy': 'A_blur_freq', 'stage': f'blur0.5_freq{freq}', 'parameter': freq, 'confidence': conf, 'p_fake': pfake, 'flipped': pred != orig_pred})

        for sigma in noise_levels:
            rng = np.random.default_rng(abs(hash((sid, label, 'B_noise', sigma))) % (2**32))
            adv = apply_noise(image_np, sigma, rng)
            pred, conf, pfake = predict_details(model, adv)
            rows.append({'sample_id': sid, 'true_label': label, 'strategy': 'B_noise', 'stage': f'noise_{sigma}', 'parameter': sigma, 'confidence': conf, 'p_fake': pfake, 'flipped': pred != orig_pred})

        for bright in brightness_levels:
            rng = np.random.default_rng(abs(hash((sid, label, 'B_noise_bright', bright))) % (2**32))
            adv = apply_noise(image_np, 0.02, rng)
            adv = apply_brightness(adv, bright)
            pred, conf, pfake = predict_details(model, adv)
            rows.append({'sample_id': sid, 'true_label': label, 'strategy': 'B_noise_bright', 'stage': f'noise0.02_bright{bright}', 'parameter': bright, 'confidence': conf, 'p_fake': pfake, 'flipped': pred != orig_pred})

    df = pd.DataFrame(rows)
    df.to_csv(out_path, index=False)
    return df

before_df = eval_model_under_attacks(base_model, BEFORE_ATTACK_PATH)
after_df = eval_model_under_attacks(robust_model, AFTER_ATTACK_PATH)

print('Saved before attacks:', BEFORE_ATTACK_PATH)
print('Saved after attacks :', AFTER_ATTACK_PATH)
print(before_df.shape, after_df.shape)

Attacking:   0%|          | 0/100 [00:00<?, ?it/s]

Attacking:   1%|          | 1/100 [00:00<01:06,  1.48it/s]

Attacking:   2%|▏         | 2/100 [00:00<00:42,  2.30it/s]

Attacking:   3%|▎         | 3/100 [00:01<00:40,  2.42it/s]

Attacking:   4%|▍         | 4/100 [00:01<00:39,  2.40it/s]

Attacking:   5%|▌         | 5/100 [00:02<00:34,  2.72it/s]

Attacking:   6%|▌         | 6/100 [00:02<00:33,  2.82it/s]

Attacking:   7%|▋         | 7/100 [00:02<00:31,  2.99it/s]

Attacking:   8%|▊         | 8/100 [00:02<00:29,  3.11it/s]

Attacking:   9%|▉         | 9/100 [00:03<00:33,  2.70it/s]

Attacking:  10%|█         | 10/100 [00:03<00:33,  2.67it/s]

Attacking:  11%|█         | 11/100 [00:04<00:36,  2.44it/s]

Attacking:  12%|█▏        | 12/100 [00:04<00:35,  2.47it/s]

Attacking:  13%|█▎        | 13/100 [00:05<00:32,  2.66it/s]

Attacking:  14%|█▍        | 14/100 [00:05<00:30,  2.77it/s]

Attacking:  15%|█▌        | 15/100 [00:05<00:28,  2.94it/s]

Attacking:  16%|█▌        | 16/100 [00:05<00:27,  3.08it/s]

Attacking:  17%|█▋        | 17/100 [00:06<00:25,  3.22it/s]

Attacking:  18%|█▊        | 18/100 [00:06<00:24,  3.38it/s]

Attacking:  19%|█▉        | 19/100 [00:06<00:23,  3.47it/s]

Attacking:  20%|██        | 20/100 [00:06<00:22,  3.54it/s]

Attacking:  21%|██        | 21/100 [00:07<00:22,  3.58it/s]

Attacking:  22%|██▏       | 22/100 [00:07<00:21,  3.68it/s]

Attacking:  23%|██▎       | 23/100 [00:07<00:20,  3.67it/s]

Attacking:  24%|██▍       | 24/100 [00:08<00:20,  3.66it/s]

Attacking:  25%|██▌       | 25/100 [00:08<00:20,  3.69it/s]

Attacking:  26%|██▌       | 26/100 [00:08<00:19,  3.75it/s]

Attacking:  27%|██▋       | 27/100 [00:08<00:20,  3.62it/s]

Attacking:  28%|██▊       | 28/100 [00:09<00:19,  3.61it/s]

Attacking:  29%|██▉       | 29/100 [00:09<00:19,  3.68it/s]

Attacking:  30%|███       | 30/100 [00:09<00:19,  3.66it/s]

Attacking:  31%|███       | 31/100 [00:09<00:18,  3.66it/s]

Attacking:  32%|███▏      | 32/100 [00:10<00:23,  2.86it/s]

Attacking:  33%|███▎      | 33/100 [00:10<00:22,  2.94it/s]

Attacking:  34%|███▍      | 34/100 [00:11<00:21,  3.05it/s]

Attacking:  35%|███▌      | 35/100 [00:11<00:20,  3.17it/s]

Attacking:  36%|███▌      | 36/100 [00:11<00:19,  3.35it/s]

Attacking:  37%|███▋      | 37/100 [00:11<00:18,  3.46it/s]

Attacking:  38%|███▊      | 38/100 [00:12<00:17,  3.53it/s]

Attacking:  39%|███▉      | 39/100 [00:12<00:16,  3.65it/s]

Attacking:  40%|████      | 40/100 [00:12<00:16,  3.74it/s]

Attacking:  41%|████      | 41/100 [00:12<00:15,  3.76it/s]

Attacking:  42%|████▏     | 42/100 [00:13<00:15,  3.75it/s]

Attacking:  43%|████▎     | 43/100 [00:13<00:15,  3.79it/s]

Attacking:  44%|████▍     | 44/100 [00:13<00:14,  3.80it/s]

Attacking:  45%|████▌     | 45/100 [00:14<00:14,  3.85it/s]

Attacking:  46%|████▌     | 46/100 [00:14<00:14,  3.78it/s]

Attacking:  47%|████▋     | 47/100 [00:14<00:13,  3.82it/s]

Attacking:  48%|████▊     | 48/100 [00:14<00:13,  3.86it/s]

Attacking:  49%|████▉     | 49/100 [00:15<00:13,  3.88it/s]

Attacking:  50%|█████     | 50/100 [00:15<00:13,  3.84it/s]

Attacking:  51%|█████     | 51/100 [00:15<00:12,  3.88it/s]

Attacking:  52%|█████▏    | 52/100 [00:15<00:12,  3.92it/s]

Attacking:  53%|█████▎    | 53/100 [00:16<00:11,  3.93it/s]

Attacking:  54%|█████▍    | 54/100 [00:16<00:11,  3.90it/s]

Attacking:  55%|█████▌    | 55/100 [00:16<00:11,  3.92it/s]

Attacking:  56%|█████▌    | 56/100 [00:16<00:11,  3.94it/s]

Attacking:  57%|█████▋    | 57/100 [00:17<00:10,  3.91it/s]

Attacking:  58%|█████▊    | 58/100 [00:17<00:10,  3.87it/s]

Attacking:  59%|█████▉    | 59/100 [00:17<00:10,  3.89it/s]

Attacking:  60%|██████    | 60/100 [00:17<00:10,  3.89it/s]

Attacking:  61%|██████    | 61/100 [00:18<00:10,  3.86it/s]

Attacking:  62%|██████▏   | 62/100 [00:18<00:09,  3.88it/s]

Attacking:  63%|██████▎   | 63/100 [00:18<00:09,  3.84it/s]

Attacking:  64%|██████▍   | 64/100 [00:18<00:09,  3.85it/s]

Attacking:  65%|██████▌   | 65/100 [00:19<00:09,  3.80it/s]

Attacking:  66%|██████▌   | 66/100 [00:19<00:09,  3.58it/s]

Attacking:  67%|██████▋   | 67/100 [00:19<00:09,  3.58it/s]

Attacking:  68%|██████▊   | 68/100 [00:20<00:08,  3.63it/s]

Attacking:  69%|██████▉   | 69/100 [00:20<00:08,  3.66it/s]

Attacking:  70%|███████   | 70/100 [00:20<00:08,  3.74it/s]

Attacking:  71%|███████   | 71/100 [00:20<00:07,  3.78it/s]

Attacking:  72%|███████▏  | 72/100 [00:21<00:07,  3.68it/s]

Attacking:  73%|███████▎  | 73/100 [00:21<00:09,  2.93it/s]

Attacking:  74%|███████▍  | 74/100 [00:21<00:08,  3.04it/s]

Attacking:  75%|███████▌  | 75/100 [00:22<00:08,  3.09it/s]

Attacking:  76%|███████▌  | 76/100 [00:22<00:07,  3.28it/s]

Attacking:  77%|███████▋  | 77/100 [00:22<00:06,  3.39it/s]

Attacking:  78%|███████▊  | 78/100 [00:23<00:06,  3.44it/s]

Attacking:  79%|███████▉  | 79/100 [00:23<00:06,  3.39it/s]

Attacking:  80%|████████  | 80/100 [00:23<00:06,  3.24it/s]

Attacking:  81%|████████  | 81/100 [00:23<00:05,  3.35it/s]

Attacking:  82%|████████▏ | 82/100 [00:24<00:05,  3.44it/s]

Attacking:  83%|████████▎ | 83/100 [00:24<00:04,  3.58it/s]

Attacking:  84%|████████▍ | 84/100 [00:24<00:04,  3.65it/s]

Attacking:  85%|████████▌ | 85/100 [00:24<00:04,  3.75it/s]

Attacking:  86%|████████▌ | 86/100 [00:25<00:03,  3.75it/s]

Attacking:  87%|████████▋ | 87/100 [00:25<00:03,  3.81it/s]

Attacking:  88%|████████▊ | 88/100 [00:25<00:03,  3.85it/s]

Attacking:  89%|████████▉ | 89/100 [00:26<00:02,  3.90it/s]

Attacking:  90%|█████████ | 90/100 [00:26<00:02,  3.83it/s]

Attacking:  91%|█████████ | 91/100 [00:26<00:02,  3.87it/s]

Attacking:  92%|█████████▏| 92/100 [00:26<00:02,  3.83it/s]

Attacking:  93%|█████████▎| 93/100 [00:27<00:01,  3.86it/s]

Attacking:  94%|█████████▍| 94/100 [00:27<00:01,  3.79it/s]

Attacking:  95%|█████████▌| 95/100 [00:27<00:01,  3.84it/s]

Attacking:  96%|█████████▌| 96/100 [00:27<00:01,  3.88it/s]

Attacking:  97%|█████████▋| 97/100 [00:28<00:00,  3.81it/s]

Attacking:  98%|█████████▊| 98/100 [00:28<00:00,  3.84it/s]

Attacking:  99%|█████████▉| 99/100 [00:28<00:00,  3.84it/s]

Attacking: 100%|██████████| 100/100 [00:28<00:00,  3.87it/s]

Attacking: 100%|██████████| 100/100 [00:28<00:00,  3.46it/s]

Attacking:   0%|          | 0/100 [00:00<?, ?it/s]

Attacking:   1%|          | 1/100 [00:00<00:30,  3.27it/s]

Attacking:   2%|▏         | 2/100 [00:00<00:31,  3.08it/s]

Attacking:   3%|▎         | 3/100 [00:00<00:31,  3.04it/s]

Attacking:   4%|▍         | 4/100 [00:01<00:29,  3.21it/s]

Attacking:   5%|▌         | 5/100 [00:01<00:28,  3.39it/s]

Attacking:   6%|▌         | 6/100 [00:01<00:27,  3.44it/s]

Attacking:   7%|▋         | 7/100 [00:02<00:26,  3.54it/s]

Attacking:   8%|▊         | 8/100 [00:02<00:27,  3.40it/s]

Attacking:   9%|▉         | 9/100 [00:02<00:25,  3.51it/s]

Attacking:  10%|█         | 10/100 [00:02<00:25,  3.53it/s]

Attacking:  11%|█         | 11/100 [00:03<00:24,  3.57it/s]

Attacking:  12%|█▏        | 12/100 [00:03<00:24,  3.62it/s]

Attacking:  13%|█▎        | 13/100 [00:03<00:23,  3.66it/s]

Attacking:  14%|█▍        | 14/100 [00:04<00:23,  3.69it/s]

Attacking:  15%|█▌        | 15/100 [00:04<00:23,  3.67it/s]

Attacking:  16%|█▌        | 16/100 [00:04<00:22,  3.73it/s]

Attacking:  17%|█▋        | 17/100 [00:04<00:22,  3.77it/s]

Attacking:  18%|█▊        | 18/100 [00:05<00:21,  3.79it/s]

Attacking:  19%|█▉        | 19/100 [00:05<00:23,  3.48it/s]

Attacking:  20%|██        | 20/100 [00:05<00:22,  3.58it/s]

Attacking:  21%|██        | 21/100 [00:05<00:21,  3.65it/s]

Attacking:  22%|██▏       | 22/100 [00:06<00:21,  3.64it/s]

Attacking:  23%|██▎       | 23/100 [00:06<00:20,  3.69it/s]

Attacking:  24%|██▍       | 24/100 [00:06<00:20,  3.75it/s]

Attacking:  25%|██▌       | 25/100 [00:06<00:19,  3.79it/s]

Attacking:  26%|██▌       | 26/100 [00:07<00:19,  3.78it/s]

Attacking:  27%|██▋       | 27/100 [00:07<00:19,  3.79it/s]

Attacking:  28%|██▊       | 28/100 [00:07<00:18,  3.84it/s]

Attacking:  29%|██▉       | 29/100 [00:08<00:19,  3.73it/s]

Attacking:  30%|███       | 30/100 [00:08<00:19,  3.65it/s]

Attacking:  31%|███       | 31/100 [00:08<00:18,  3.69it/s]

Attacking:  32%|███▏      | 32/100 [00:08<00:18,  3.68it/s]

Attacking:  33%|███▎      | 33/100 [00:09<00:18,  3.72it/s]

Attacking:  34%|███▍      | 34/100 [00:09<00:17,  3.71it/s]

Attacking:  35%|███▌      | 35/100 [00:09<00:17,  3.77it/s]

Attacking:  36%|███▌      | 36/100 [00:09<00:17,  3.71it/s]

Attacking:  37%|███▋      | 37/100 [00:10<00:16,  3.71it/s]

Attacking:  38%|███▊      | 38/100 [00:10<00:16,  3.77it/s]

Attacking:  39%|███▉      | 39/100 [00:10<00:16,  3.75it/s]

Attacking:  40%|████      | 40/100 [00:11<00:16,  3.74it/s]

Attacking:  41%|████      | 41/100 [00:11<00:15,  3.76it/s]

Attacking:  42%|████▏     | 42/100 [00:11<00:15,  3.81it/s]

Attacking:  43%|████▎     | 43/100 [00:11<00:14,  3.81it/s]

Attacking:  44%|████▍     | 44/100 [00:12<00:14,  3.87it/s]

Attacking:  45%|████▌     | 45/100 [00:12<00:14,  3.83it/s]

Attacking:  46%|████▌     | 46/100 [00:12<00:13,  3.87it/s]

Attacking:  47%|████▋     | 47/100 [00:12<00:13,  3.88it/s]

Attacking:  48%|████▊     | 48/100 [00:13<00:13,  3.89it/s]

Attacking:  49%|████▉     | 49/100 [00:13<00:13,  3.87it/s]

Attacking:  50%|█████     | 50/100 [00:13<00:12,  3.88it/s]

Attacking:  51%|█████     | 51/100 [00:13<00:12,  3.82it/s]

Attacking:  52%|█████▏    | 52/100 [00:14<00:12,  3.87it/s]

Attacking:  53%|█████▎    | 53/100 [00:14<00:12,  3.83it/s]

Attacking:  54%|█████▍    | 54/100 [00:14<00:11,  3.87it/s]

Attacking:  55%|█████▌    | 55/100 [00:14<00:11,  3.87it/s]

Attacking:  56%|█████▌    | 56/100 [00:15<00:11,  3.90it/s]

Attacking:  57%|█████▋    | 57/100 [00:15<00:11,  3.86it/s]

Attacking:  58%|█████▊    | 58/100 [00:15<00:10,  3.89it/s]

Attacking:  59%|█████▉    | 59/100 [00:15<00:10,  3.87it/s]

Attacking:  60%|██████    | 60/100 [00:16<00:10,  3.90it/s]

Attacking:  61%|██████    | 61/100 [00:16<00:10,  3.88it/s]

Attacking:  62%|██████▏   | 62/100 [00:16<00:09,  3.89it/s]

Attacking:  63%|██████▎   | 63/100 [00:16<00:09,  3.89it/s]

Attacking:  64%|██████▍   | 64/100 [00:17<00:09,  3.86it/s]

Attacking:  65%|██████▌   | 65/100 [00:17<00:09,  3.84it/s]

Attacking:  66%|██████▌   | 66/100 [00:17<00:08,  3.87it/s]

Attacking:  67%|██████▋   | 67/100 [00:17<00:08,  3.88it/s]

Attacking:  68%|██████▊   | 68/100 [00:18<00:08,  3.83it/s]

Attacking:  69%|██████▉   | 69/100 [00:18<00:08,  3.81it/s]

Attacking:  70%|███████   | 70/100 [00:18<00:07,  3.79it/s]

Attacking:  71%|███████   | 71/100 [00:19<00:07,  3.80it/s]

Attacking:  72%|███████▏  | 72/100 [00:19<00:07,  3.77it/s]

Attacking:  73%|███████▎  | 73/100 [00:19<00:07,  3.81it/s]

Attacking:  74%|███████▍  | 74/100 [00:19<00:06,  3.83it/s]

Attacking:  75%|███████▌  | 75/100 [00:20<00:06,  3.86it/s]

Attacking:  76%|███████▌  | 76/100 [00:20<00:06,  3.83it/s]

Attacking:  77%|███████▋  | 77/100 [00:20<00:06,  3.83it/s]

Attacking:  78%|███████▊  | 78/100 [00:20<00:05,  3.73it/s]

Attacking:  79%|███████▉  | 79/100 [00:21<00:05,  3.75it/s]

Attacking:  80%|████████  | 80/100 [00:21<00:05,  3.77it/s]

Attacking:  81%|████████  | 81/100 [00:21<00:04,  3.81it/s]

Attacking:  82%|████████▏ | 82/100 [00:21<00:04,  3.78it/s]

Attacking:  83%|████████▎ | 83/100 [00:22<00:04,  3.81it/s]

Attacking:  84%|████████▍ | 84/100 [00:22<00:04,  3.68it/s]

Attacking:  85%|████████▌ | 85/100 [00:22<00:04,  3.72it/s]

Attacking:  86%|████████▌ | 86/100 [00:23<00:03,  3.74it/s]

Attacking:  87%|████████▋ | 87/100 [00:23<00:03,  3.69it/s]

Attacking:  88%|████████▊ | 88/100 [00:23<00:03,  3.74it/s]

Attacking:  89%|████████▉ | 89/100 [00:23<00:02,  3.79it/s]

Attacking:  90%|█████████ | 90/100 [00:24<00:02,  3.82it/s]

Attacking:  91%|█████████ | 91/100 [00:24<00:02,  3.80it/s]

Attacking:  92%|█████████▏| 92/100 [00:24<00:02,  3.84it/s]

Attacking:  93%|█████████▎| 93/100 [00:24<00:01,  3.84it/s]

Attacking:  94%|█████████▍| 94/100 [00:25<00:01,  3.85it/s]

Attacking:  95%|█████████▌| 95/100 [00:25<00:01,  3.81it/s]

Attacking:  96%|█████████▌| 96/100 [00:25<00:01,  3.83it/s]

Attacking:  97%|█████████▋| 97/100 [00:25<00:00,  3.83it/s]

Attacking:  98%|█████████▊| 98/100 [00:26<00:00,  3.85it/s]

Attacking:  99%|█████████▉| 99/100 [00:26<00:00,  3.68it/s]

Attacking: 100%|██████████| 100/100 [00:26<00:00,  3.29it/s]

Attacking: 100%|██████████| 100/100 [00:26<00:00,  3.73it/s]

Saved before attacks: /Users/arulkevin/Desktop/psg_hackathon/Feb-2026-Hackathon/Phase 3/outputs/m4_strategy_results_original.csv
Saved after attacks : /Users/arulkevin/Desktop/psg_hackathon/Feb-2026-Hackathon/Phase 3/outputs/m4_strategy_results_robust.csv
(1500, 8) (1500, 8)

In [9]:
# Build robustness comparison table

def summarize_attacks(df):
    attack_df = df[df['strategy'] != 'original'].copy()
    base = df[df['strategy'] == 'original'][['sample_id', 'true_label', 'confidence', 'p_fake']].rename(columns={'confidence': 'base_conf', 'p_fake': 'base_p_fake'})
    attack_df = attack_df.merge(base, on=['sample_id', 'true_label'], how='left')
    attack_df['conf_drop'] = attack_df['base_conf'] - attack_df['confidence']
    attack_df['p_fake_abs_delta'] = (attack_df['p_fake'] - attack_df['base_p_fake']).abs()

    sample_strat = attack_df.groupby(['sample_id', 'strategy'], as_index=False)['flipped'].max()
    a_mask = sample_strat['strategy'].isin(['A_blur', 'A_blur_freq'])
    b_mask = sample_strat['strategy'].isin(['B_noise', 'B_noise_bright'])

    flip_rate_a = sample_strat[a_mask]['flipped'].mean() if a_mask.any() else np.nan
    flip_rate_b = sample_strat[b_mask]['flipped'].mean() if b_mask.any() else np.nan
    flip_rate_all = sample_strat['flipped'].mean() if len(sample_strat) else np.nan

    mean_drop_a = attack_df[attack_df['strategy'].isin(['A_blur', 'A_blur_freq'])]['conf_drop'].mean()
    mean_drop_b = attack_df[attack_df['strategy'].isin(['B_noise', 'B_noise_bright'])]['conf_drop'].mean()
    mean_pfake_delta = attack_df['p_fake_abs_delta'].mean()

    return {
        'Flip_Rate_Strategy_A': float(flip_rate_a),
        'Flip_Rate_Strategy_B': float(flip_rate_b),
        'Flip_Rate_Overall': float(flip_rate_all),
        'Mean_Confidence_Drop_A': float(mean_drop_a),
        'Mean_Confidence_Drop_B': float(mean_drop_b),
        'MeanAbsDelta_p_fake_All_Attacks': float(mean_pfake_delta),
    }

before_metrics = summarize_attacks(before_df)
after_metrics = summarize_attacks(after_df)

rows = []
for k in before_metrics:
    rows.append({'Metric': k, 'Original_Model_Value': before_metrics[k], 'Improved_Model_Value': after_metrics[k]})

comparison_df = pd.DataFrame(rows)
comparison_df.to_csv(ROBUSTNESS_CSV_PATH, index=False)
print('Saved:', ROBUSTNESS_CSV_PATH)
comparison_df

Saved: /Users/arulkevin/Desktop/psg_hackathon/Feb-2026-Hackathon/Phase 3/outputs/robustness_comparison.csv

                            Metric  Original_Model_Value  Improved_Model_Value
0             Flip_Rate_Strategy_A              0.045000              0.155000
1             Flip_Rate_Strategy_B              0.090000              0.075000
2                Flip_Rate_Overall              0.067500              0.115000
3           Mean_Confidence_Drop_A             -0.029532             -0.010307
4           Mean_Confidence_Drop_B              0.029154             -0.009184
5  MeanAbsDelta_p_fake_All_Attacks              0.046534              0.072111

In [10]:
# Final recommendation markdown

def _rel(path_like):
    p = Path(path_like)
    try:
        return p.resolve().relative_to(PROJECT_ROOT).as_posix()
    except Exception:
        return str(p)

report = []
report.append('# Final Recommendation (Member 4)')
report.append('')
report.append('## Inputs Used')
report.append(f'- M1 baseline attacks: `{_rel(M1_RESULTS_PATH)}`')
report.append(f'- M2 minimal-change summary: `{_rel(M2_RESULTS_PATH)}`')
report.append(f'- M3 blindspot report: `{_rel(M3_REPORT_PATH)}`')
report.append(f'- M3 attack correlation: `{_rel(M3_CORR_PATH)}`')
report.append('')
report.append('## Chosen Defense Strategy')
report.append(f'- Primary vulnerability from M3: `{primary_attack_family}`')
report.append(f'- Implemented defense: `{defense_strategy}`')
if defense_strategy == 'strategy_a_robust_aug':
    report.append('- Applied robust transform with Gaussian blur + random grayscale + mild color jitter to reduce texture/high-frequency over-reliance.')
elif defense_strategy == 'strategy_b_noise_aug':
    report.append('- Applied noise/photometric-focused augmentation to reduce sensitivity to noise and brightness shifts.')
else:
    report.append('- Applied mixed robust augmentation as fallback.')
report.append('')
report.append('## Prototype Training')
report.append(f'- Checkpoint loaded: `{_rel(CHECKPOINT_PATH)}`')
report.append(f'- Fine-tune epochs: `{EPOCHS}` (prototype setting)')
report.append(f'- Train samples used: `{len(train_ds)}`')
report.append(f'- Val samples used: `{len(val_ds)}`')
report.append(f'- Robust model saved: `{_rel(ROBUST_MODEL_PATH)}`')
report.append('')
report.append('## Stress-Test Comparison (Same Attack Families)')
for _, r in comparison_df.iterrows():
    m = r['Metric']
    b = r['Original_Model_Value']
    a = r['Improved_Model_Value']
    report.append(f'- {m}: before={b:.6f}, after={a:.6f}, delta={a-b:+.6f}')
report.append('')
report.append('## Deliverables')
report.append(f'- `robust_model_prototype.pt`: `{_rel(ROBUST_MODEL_PATH)}`')
report.append(f'- `robustness_comparison.csv`: `{_rel(ROBUSTNESS_CSV_PATH)}`')
report.append(f'- `final_recommendation.md`: `{_rel(FINAL_RECO_PATH)}`')

FINAL_RECO_PATH.write_text('\n'.join(report), encoding='utf-8')
print('Saved:', FINAL_RECO_PATH)
print('\n'.join(report[:40]))

Saved: /Users/arulkevin/Desktop/psg_hackathon/Feb-2026-Hackathon/Phase 3/outputs/final_recommendation.md
# Final Recommendation (Member 4)

## Inputs Used
- M1 baseline attacks: `Phase 3/outputs/strategy_results.csv`
- M2 minimal-change summary: `Phase 3/outputs/min_change_summary.csv`
- M3 blindspot report: `Phase 3/outputs/blindspot_analysis.md`
- M3 attack correlation: `Phase 3/outputs/m3_attack_correlation.csv`

## Chosen Defense Strategy
- Primary vulnerability from M3: `Strategy A (Spatial + Frequency)`
- Implemented defense: `strategy_a_robust_aug`
- Applied robust transform with Gaussian blur + random grayscale + mild color jitter to reduce texture/high-frequency over-reliance.

## Prototype Training
- Checkpoint loaded: `Phase1/cifake_resnet18_final.pt`
- Fine-tune epochs: `3` (prototype setting)
- Train samples used: `4000`
- Val samples used: `1000`
- Robust model saved: `Phase 3/outputs/robust_model_prototype.pt`

## Stress-Test Comparison (Same Attack Families)
- Flip_Rate_Strategy_A: before=0.045000, after=0.155000, delta=+0.110000
- Flip_Rate_Strategy_B: before=0.090000, after=0.075000, delta=-0.015000
- Flip_Rate_Overall: before=0.067500, after=0.115000, delta=+0.047500
- Mean_Confidence_Drop_A: before=-0.029532, after=-0.010307, delta=+0.019225
- Mean_Confidence_Drop_B: before=0.029154, after=-0.009184, delta=-0.038338
- MeanAbsDelta_p_fake_All_Attacks: before=0.046534, after=0.072111, delta=+0.025577

## Deliverables
- `robust_model_prototype.pt`: `Phase 3/outputs/robust_model_prototype.pt`
- `robustness_comparison.csv`: `Phase 3/outputs/robustness_comparison.csv`
- `final_recommendation.md`: `Phase 3/outputs/final_recommendation.md`